import Head from "next/head";
const Shows = ()=>{
    return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Sono lo shows
      </div>
      
    </>
    )
}

export default Shows
